version: '3.3'

services:
  mariadb:
    image: mariadb:inception
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    env_file: .env  # ✅ still used for DB_NAME, DB_USER
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_root_password
      - db_password


  wordpress:
    image: wordpress:inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    secrets:
      - wp_admin_password
      - wp_secondary_password
      - db_password  # needed to connect to DB

  nginx:
    image: nginx:inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb  # 🔁 REPLACE with actual login if needed
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password
  db_password:
    file: ./secrets/db_password
  wp_admin_password:
    file: ./secrets/wp_admin_password
  wp_secondary_password:
    file: ./secrets/wp_secondary_password
