version: '3.3'  # 👈 Specifies the Compose file format version (3.3 supports networks, volumes, restart policies)

services:
  mariadb:
    image: mariadb:inception
    build: 
      context: ./requirements/mariadb   # 👈 Build MariaDB image from a local Dockerfile (✅ Must build, not pull)
      dockerfile: Dockerfile
    container_name: mariadb         # 👈 Name for easy reference/logging
    restart: always                 # ✅ Required: container must auto-restart on crash
    env_file: .env                  # ✅ Required: credentials must not be hardcoded, read from .env
    volumes:
      - mariadb_data:/var/lib/mysql  # ✅ Required: persist DB data to a bind-mounted host volume
    networks:
      - inception                    # ✅ Required: all services must share an internal network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}  # ✅ Use environment variable from .env to pass root password securely

  wordpress:
    image: wordpress:inception
    build:
      context: ./requirements/wordpress # ✅ Must build from Dockerfile (no DockerHub pulls allowed)
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always                 # ✅ Required restart policy
    env_file: .env                  # ✅ Use same env file for DB access credentials
    depends_on:
      - mariadb                    # 👈 Ensure MariaDB starts first
    volumes:
      - wordpress_data:/var/www/html  # ✅ Required: store WordPress files in a host-mounted directory
    networks:
      - inception                   # ✅ Must be on the same internal Docker network


  nginx:
    image: nginx:inception
    build:
      context: ./requirements/nginx     # ✅ Must build your own NGINX image with SSL
      dockerfile: Dockerfile
    container_name: nginx
    restart: always                 # ✅ Required: restart on crash
    ports:
      - "443:443"                  # ✅ Only port allowed: HTTPS over 443
    depends_on:
      - wordpress                   # 👈 Ensure WordPress is running before starting NGINX
    volumes:
      - wordpress_data:/var/www/html  # ✅ Mount WordPress files so NGINX can serve them
    networks:
      - inception                   # ✅ All services must share the same Docker bridge network

# ✅ Required volumes, bind-mounted under /home/<login>/data
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none                   # 👈 Required for bind mount
      device: /home/login/data/mariadb  # ✅ Required mount point (host path)
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/login/data/wordpress  # ✅ Must persist WordPress site files here
      o: bind

# ✅ Required internal network for inter-container communication
networks:
  inception:
    driver: bridge  # 👈 Default Docker bridge network for internal service communication
